channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.7
  - nodejs=16.13.0
  - pip=20.1

  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==12.2.0 # https://rpaframework.org/releasenotes.html
      - rpaframework-recognition==1.0.0
      - rpaframework-windows==2.0.0
      - rpaframework-google==2.0.0
      - robotframework-browser==11.1.1
      - robotframework-camunda==2.0.0
      - PyMuPDF==1.19.3
      - pytesseract==0.3.8
      - opencv-python==4.5.5.62
      - numpy==1.21.5
      - pywin32==301
      - playwright==1.17.2

rccPostInstall:
  - rfbrowser init
